id: IB70E4D76
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T17:54:03+00:00'
last_modified: '2022-06-08T17:22:23.013204+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W27867
  title: ལྕེ་བཙུན་སྙིང་ཐིག་གི་ཆོས་སྐོར།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    B828:
      image_group_id: I4484
      title: ''
      total_pages: 760
      order: 1
      base_file: B828.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
