id: IB70E4D76
legacy_id: P010766
ocr_import_info:
  bdrc_scan_id: W27867
  source: bdrc
  ocr_info:
    timestamp: '2020-03-31T17:49:19'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T07:33:00.503810+00:00'
last_modified: 2022-09-02 15:33:43.679044
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W27867
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW27867
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ལྕེ་བཙུན་སྙིང་ཐིག་གི་ཆོས་སྐོར།
  author: མཁྱེན་བརྩེའི་དབང་པོ།
statistics:
  ocr_word_mean_confidence_index: 0.7298598573021057
  ocr_word_median_confidence_index: 0.800000011920929
quality: null
bases:
  I4484:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4484
      total_pages: 760
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I4484.txt
    statistics:
      ocr_word_median_confidence_index: 0.800000011920929
      ocr_word_mean_confidence_index: 0.7298598573021057
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
