id: P010766
initial_creation_type: ocr
source_metadata:
  id: bdr:W27867
  title: ལྕེ་བཙུན་སྙིང་ཐིག་གི་ཆོས་སྐོར།
  author: ''
  volumes:
    8e2623de9e4f4110b8acd290facea483:
      image_group_id: I4484
      title: ''
      volume_number: 1
      total_pages: 760
